### ISSUE TITLE
parallelSeriesEquivalence.tex references nonexistent graphic parallelSeriesEquivalent.pdf

### ISSUE THREAD

**Issue by mgiustina** [DanielSank/theory#8] opened 2017-02-01 23:58 UTC
In line 25.

Presumably the python figure maker should take care of this. When I try to build `circuits` with `$ pdflatex circuits.tex`, the figure is never created.

**Comment by DanielSank** [comment] 2017-02-02 00:11
Yeah, I haven't gone through and added a figure-maker script for every document. In the meanwhile, to do it yourself, load the svg in Inkscape and then just save-as pdf.

**Comment by mgiustina** [comment] 2017-02-02 00:11
`$ python make-figures.py
sh: line 4: inkscape: command not found`

**Comment by DanielSank** [comment] 2017-02-02 00:11
Yep, install inkscape. Or use your favorite svg->pdf tool.

**Comment by DanielSank** [comment] 2017-02-02 00:12
Oh, hah, the python script is already there. Ok in that case this issue is a "wontfix" because the problem is that you have to install inkscape. Maybe I should put that in big letters in the README...

**Comment by DanielSank** [comment] 2017-02-02 00:15
Sorry, I shouldn't have closed this so fast. Is the issue resolved to your satisfaction?

**Comment by mgiustina** [comment] 2017-02-02 00:19
You might want to update the readme to mention that not only tex but also python and inkscape are needed.

**Comment by DanielSank** [comment] 2017-02-02 00:24
Added an issue about that.

**Comment by DanielSank** [comment] 2017-02-02 00:24
Based on comment in #9, closing.

**Closed** 2017-02-02 00:24 UTC
